openapi: 3.1.1
info:
  title: Ping API
  description: Простое API для проверки доступности сервера.
  version: 1.0.0
servers:
  - url: http://127.0.0.1


tags:
  - name: System
    description: Системные операции
  - name: Item
    description: Работа с объявлениями
  - name: Categories
    description: Работа с категориями
  - name: Search
    description: Поиск

paths:
  /ping:
    $ref: './paths/ping.yml#/ping'
  /api/v1/item:
    $ref: './paths/item.yml#/itemCollection'
  /api/v1/item/{item_id}:
    $ref: './paths/item.yml#/itemById'


  /api/v1/categories:
    $ref: './paths/categories.yml#/categoriesCollection'

  /api/v1/search:
    $ref: './paths/search.yml#/search'

components:
  schemas:
    $ref: './components/schemas.yml'
  responses:
    $ref: './components/responses.yml'
