openapi: 3.1.1
info:
  title: Ping API
  description: Простое API для проверки доступности сервера.
  version: 1.0.0
servers:
  - url: http://127.0.0.1

tags:
  - name: System
    description: Системные операции
  - name: Listing
    description: Работа с объявлениями
  - name: Categories
    description: Работа с категориями
  - name: Search
    description: Поиск

paths:
  /ping:
    $ref: './paths/ping.yml#/ping'
  /api/v1/listing:
    $ref: './paths/listing.yml#/listingCollection'
  /api/v1/listing/{listing_id}:
    $ref: './paths/listing.yml#/listingById'
  /api/v1/categories:
    $ref: './paths/categories.yml#/categoriesCollection'
  /api/v1/search:
    $ref: './paths/search.yml#/search'

components:
  schemas:
    PingResponse:
      type: object
      properties:
        ping:
          type: string
          example: pong
      required:
        - ping

    ListingRequest:
      type: object
      properties:
        title:
          type: string
          example: Часы
        text:
          type: string
          example: супер товар
      required:
        - title
        - text

    ListingResponse:
      type: object
      properties:
        id:
          type: string
          example: "123e4567-e89b-12d3-a456-426614174000"
        title:
          type: string
          example: Часы
        text:
          type: string
          example: супер товар
      required:
        - id
        - title
        - text

  responses:
    NotFound:
      description: Объект не найден
      content:
        application/json:
          schema:
            type: object
            properties:
              code:
                type: string
                example: NotFound
              description:
                type: string
                example: Объект не найден
