version: '3.8'

services:
  postgres:
    image: postgres:16.6-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  argon:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: argon
    # Передаём всё, что есть в .env, внутрь контейнера
    environment:
      # Передаём всё, что есть в .env, внутрь контейнера
      - APP_DB_URL="postgresql://postgres:postgres@db:5432/postgres"
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local
