version: '3'
services:
  redoc:
    image: nginx:alpine
    volumes:
      - ./openapi.yml:/usr/share/nginx/html/openapi.yml:ro
      - ./index.html:/usr/share/nginx/html/index.html:ro
    ports:
      - "8082:80"
