# Порт приложения
port = 8080

# Настройки базы данных
[db]
url = "postgresql://postgres:postgres@127.0.0.1:5435/postgres"

# Настройки логгера
[logger]
level = "info"

[binance]
local = true
apiKey = ""
secretKey = ""

[nominatim]
baseUrl = "https://nominatim.openstreetmap.org/"