# Порт приложения
[app]
name = "Argon"
serverUrl = "http://127.0.0.1:8080"
port = 8080

# Настройки базы данных
[db]
url = "postgresql://postgres:postgres@127.0.0.1:5435/postgres"

# Настройки MinIO
[minio]
endpoint = "localhost:9000"
user = "minioadmin"
password = "minioadmin"
bucket = "images"

# Настройки логгера
[logger]
level = "info"

[binance]
local = true
apiKey = ""
secretKey = ""

[nominatim]
baseUrl = "https://nominatim.openstreetmap.org/"