name: Go Lint

on:
  push:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23.2'

      - name: Lint & Vet
        run: |
          go vet ./...
          # Установите golangci-lint, если нужно
          # go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
          # golangci-lint run
